### PR TITLE
Hot data storage

### PR DESCRIPTION
**Pull request by melan**
This pull request has a feature of "Hot data cache" - another whisper storage to keep metrics with short retention time so serve regular monitoring requests. This Hot data location can be put on a in-memory file system so all requests will be served much faster.

Use case: we have a lot of dashboards with time window from -2 hours till now and reading from the regular HDD is slow and expensive. As an alternative we will use this feature. Web app can also read from both of the locations and choose hot data location if it can provide enough data.

Hot data cache has own aggregation and storage schemas setup. My assumption was that storage schema for the hot cache should be a maximum frequency but for few hours only.

### CODE REVIEW

**Comment by SEJeff** [comment]
This is a really cool feature and you've put a lot of work into it, but I do worry about such an intrusive change with no tests.

Also, can a similar thing not be done with ramfs and dm-cache? Having used dm-cache for production workloads with ssds acting as caches for SATA drives I know it works super well. You'll need a newer distro like CentOS7 or RHEL7 however.

I'm just worried that if this feature can be done with a newer distro with no code changes that is a much better overall solution. Take a look at:

blog.kylemanna.com/linux/2013/06/30/ssd-caching-using-dmcache-tutorial/

**Comment by obfuscurity** [comment]
At the risk of sounding negative, I'm not crazy about this change. Clearly you put a lot of effort into this and I applaud you for that, but it seems as though your time (and company's money) would've been far better invested in upgrading to SSDs.

From a technical perspective, there's a lot of code (and configuration) duplication, leading to unnecessary complexity. Not to mention you're basically adding more psuedo-cache for a time-series format (Whisper) that's eventually going to be superseded by Ceres, Cyanite, InfluxDB, etc.

In an ideal world this "hot data storage" would be added as a pluggable storage backend instead, although I haven't looked closely enough at your patch to realize how feasible this would be.

**Comment by melan** [comment]
Thanks for that fast feedback. I'll check dm-cache, probably this tool may help. Servers with all SSDs isn't an option yet.

I added tests into a graphite-web project to test this feature a little. I did my the best to test carbon also, but I smashed my head trying to understand how to test all of the processors, plugins, writers, etc. I will write these test if you can help a little with advises which way to go.

Do you have any guidelines about implementation of the Hot storage as a pluggable backend?

Thanks

**Comment by obfuscurity** [comment]
http://graphite.readthedocs.org/en/latest/storage-backends.html

**Comment by melan** [comment]
Thanks for the link. I read about pluggable backend, but my feature is a different thing: it doesn't replace a backend, but enhance it. I would say this hot-data feature should work on top of the pluggable backends: it should be possible to use non-whisper backend to store that hot data.

Probably there should be a section in the config for the backend setup with some kind of connection string, like: __whisper:///opt/graphite/storage/whisper__ and something different for other kinds of the storage. So there will be 2 parameters: `BACKEND_CONNECTION_STRING` and `HOT_DATA_BACKEND_CONNECTION_STRING` or something like that.

**Comment by obfuscurity** [comment]
It seems to me that the desired functionality would be better implemented within Carbon's native caching layer, i.e. the cache would support some sort of TTL feature wherein it continues to retain metrics in-memory even after they've been flushed to disk.

**Comment by melan** [comment]
Internal cache was one of the options. But webapp reads files first and only after that cache. So this need to be changed. E.g. webapp should do all queries through the cache only and never touch files directly. Also this solution will cause more changes in the carbon-cache to implement TTL, reuse current retention policies definition logic, etc.

I decided to do it as simple as possible.

**Pull request closed without merging**
