### PR TITLE
aggregator: allow to use a bounded expiring cache to limit memory usage

### PR DESCRIPTION
**Pull request by iksaif**
Depend on https://github.com/graphite-project/carbon/pull/638

### CODE REVIEW

**Comment by wdauchy** [comment]
I guess there is one commit which should not be here (	Use requirements.txt for tox) since it is already present in the previous MR
:-1:

**Comment by iksaif** [comment]
It's because it depends on the other one. I don't know how to do 'dependent' pull requests on github. Once the other is merged the requirements.txt commit will disappear (except the part with cachetools)

**Comment by deniszh** [comment]
@iksaif: I also don't know how to properly did dependent PRs.
https://stackoverflow.com/questions/26619478/are-dependent-pull-requests-in-github-possible

Adding changes from other commits doesn't help either, this PR should be rebased anyway.

**Comment by deniszh** [comment]
Adding `cachetools` as another mandatory module? Meh.
Could we use something lightweight but "built-in in carbon code"?

**Comment by iksaif** [comment]
IMOH cachetools is very lightweight, it contains only what is necessary and is also compatible with all versions of python and all OSes.

Re-implementing an expiring LRU cache is tricky, and I tried write something for carbon only, but I ended up duplicating most of what cachetools is doing :/

**Comment by iksaif** [comment]
FYI: I tried this patch on a pretty load environment and it seems to cap the used memory as expected:

before:
carbon-before

after:
carbon-after

**Comment by iksaif** [comment]
Done.
I'd keep that in master :).

**Comment by wdauchy** [comment]
:+1:

**Comment by deniszh** [comment]
Ah, `carbon.conf` ofc. 🤦‍♂️

**Comment by iksaif** [comment]
Any objection ?

**Comment by deniszh** [comment]
No objection

**Pull request merged**
