### PR TITLE
Monkeypatch twisted logger to fix thread/umask bug (0.9.x)

### PR DESCRIPTION
**Pull request by obfuscurity**
This is a proposed fix from @jacobrichard for the [Twisted umask race bug](https://twistedmatrix.com/trac/ticket/7026) as reported in #82. It would be **really** nice to finally squash this 5+ year-old bug, once and for all. This PR includes the cherry-picked patch from #459.

**PLEASE TEST THIS CHANGE AND REPORT BACK**

### CODE REVIEW

**Comment by ShalomCohen** [comment]
O.K.
How can I apply that fix to graphite 0.9.10? for whatever reason the 2nd machine of the graphite cluster is having tons of those permission issues and I would like to avoid the find in cron. I tried replacing the log.py file with your committed file unsuccessfully so far.

**Comment by obfuscurity** [comment]
@ShalomCohen Please don't hijack this PR with questions about back-porting this to an unsupported release. After this gets merged you're welcome to open an issue (or Q&A question in Launchpad) and reference this and someone might be able to assist you.

**Comment by deniszh** [comment]
I never faced problem mentioned in #82 TBH, but my testing cluster with patch above running for couple of hours w/o any issues and/or performance impact.

**Comment by ShalomCohen** [comment]
Denis,

I actually got some inputs, I built 2 clusters of graphite with 6 machines
each, each machine with raid 0 of 5 SSDs for IO performance.
Those clusters are replication of one each other and each cluster seperatly
consume currently about 10M metrics a minute (and they easily handle double
of that based on resource utilization).
Anyhow, only the 2nd machine in the cluster that is being used for reading
the metrics have a bunch of those permission issues once a week or so(very
sporadic occurrences).
To see it in labs you'll need a lot of luck, BTW someone else also tan into
it on his second cluster node(there is probably higher probability for it
to happen with the metrics that mach the second instance using carbon hash).
On Oct 16, 2015 11:00 AM, "Denis Zhdanov" <notifications@github.com> wrote:

> I never faced problem mentioned in #82
> <https://github.com/graphite-project/carbon/issues/82> TBH, but my
> testing cluster with patch above running for couple of hours w/o any issues
> and/or performance impact.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/graphite-project/carbon/pull/460#issuecomment-148739976>
> .
>

-- 
The above terms reflect a potential business arrangement, are provided solely 
as a basis for further discussion, and are not intended to be and do not 
constitute a legally binding obligation. No legally binding obligations will 
be created, implied, or inferred until an agreement in final form is executed 
in writing by all parties involved.

This email and any attachments hereto may be confidential or privileged. 
 If you received this communication by mistake, please don't forward it to 
anyone else, please erase all copies and attachments, and please let me 
know that it has gone to the wrong person. Thanks.

**Comment by deniszh** [comment]
Hi @ShalomCohen,
Sorry, my response was mostly for @obfuscurity - I mean, patch at least bring no issues - so, it's quite safe to apply. :)
My testing cluster is not a lab cluster - it's working cluster for test environment, but yes, load is quite small though - 300K/metrics/min... 
You can try to apply patch to 0.9.10 branch but I think it's too old - please upgrade at least for whisper 0.9.12 and apply patch over it.

**Pull request merged**
