### PR TITLE
protocols: support SO_REUSEPORT

### PR DESCRIPTION
**Pull request by wdauchy**
this will avoid the need to bind each carbon process to a different port
and balance the traffic with iptables rules

this requires linux >= 3.9

patches are on their way to support reuseport directly in twisted

### CODE REVIEW

**Comment by iksaif** [comment]
That would be super useful ! @dzhdanov what do you think ?
@wdauchy  maybe add some comments with a link to the twisted PR in the code ?

**Comment by wdauchy** [comment]
@iksaif comment added in class definition

**Comment by iksaif** [comment]
(please wait for a review from somebody else :) )

**Comment by deniszh** [comment]
It's backward compatible, right?

**Comment by wdauchy** [comment]
@deniszh yes it is; even if users put same port on different relay config, it will just work if they use linux >= 3.9

**Comment by wdauchy** [comment]
@deniszh FYI I had to slightly adapt my commit for 1.0.x, see https://github.com/criteo-forks/carbon/commit/fbe31940c7f26eef852c80dde04873cc6da30d48

**Pull request merged**
