### PR TITLE
Add MAX_RECEIVER_CONNECTIONS setting.

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
Limits the number of 'connectedMetricReceiverProtocols' that a given
receiver can handle at any given time.

This is to prevent, for example, a carbon-relay opening up thousands of
connections to a carbon-cache service, both reducing the throughput of
the service and causing out of TCP memory errors.

Should also fix the observed behaviour I was trying to resolve in #513

### CODE REVIEW

**Comment by iain-buclaw-sociomantic** [comment]
Holy cow, how on earth did I not see the ``METRIC_CLIENT_IDLE_TIMEOUT`` setting.  Surely this should have a value other than ``None``.

OK, removing first commit, but keeping the latter as it was useful for diagnosis.

**Comment by iain-buclaw-sociomantic** [comment]
Actually, no.  I've reverted my mind, I'll keep this as is for now.

**Comment by mleinart** [comment]
Awesome

**Comment by iain-buclaw-sociomantic** [comment]
Thanks.

**Pull request merged**
