### PR TITLE
Another test fix try

### PR DESCRIPTION
**Pull request by deniszh**

### CODE REVIEW

**Comment by deniszh** [comment]
Ok, by default Travis use system `pip` and `virtualenv`. I tried to upgrade it before - it works fine now. 
Should we do that for all envs? Or keep it only for 2.7?
@piotr1212 @DanCech @ploxlin ?

**Comment by deniszh** [comment]
Looking for [Graphite-web results](https://github.com/graphite-project/graphite-web/pull/2530) I think it's a good idea to test on latest pip and virtualenv.

**Comment by ploxiln** [comment]
I'd lean towards just upgrading pip/virtualenv for python2.7 - following the other patterns, something like

```
  - if [[ '$TOXENV' == py2* ]]; then pip install --upgrade pip virtualenv; fi
```

(I suspect the `bash -c "..."` wrapper isn't necessary, but that's a separate thing that could be simplified later I guess.)

But anyway, no significant objection to doing it your way, that's also fine.

**Comment by deniszh** [comment]
@ploxiln:  Maybe you're right. Let's stick to 2.7 for now.

**Comment by ploxiln** [comment]
looks good, thanks :)
👍

**Comment by deniszh** [comment]
Will merge that for now and trigger tests in all non-merged PRs.

**Pull request merged**
