### PR TITLE
Synchronize calls to MetricCache.drain_metric from writer thread

### PR DESCRIPTION
**Pull request by mleinart**
The writer thread drains from the cache in a separate thread from the reactor. This sometimes leads to weird race conditions (e.g. negative cache size metrics). Instead, run the cache drain on the main reactor
thread (the place where the cache is written to).

This keeps the rest of the draining logic (cache sorting, etc) in the writer thread so as not to block the event loop.

I've done some basic performance testing on this, the expectation being that there shouldn't be much difference. The comparisons I did show no difference in throughput but CPU seemed to be a little more consistent (same moving avg, smaller range).

I'd love if someone could canary this in production and report back

### CODE REVIEW

**Comment by iain-buclaw-sociomantic** [comment]
I did give this a try, however the carbon-cache service failed to start.

**Comment by mleinart** [comment]
@iain-buclaw-sociomantic Do you have an error you can paste?

**Comment by iain-buclaw-sociomantic** [comment]
```
Traceback (most recent call last):
  File "/srv/graphite/bin/carbon-cache.py", line 32, in <module>
    run_twistd_plugin(__file__)
  File "/srv/graphite/site-packages/carbon/util.py", line 96, in run_twistd_plugin
    config.parseOptions(twistd_options)
  File "/srv/graphite/site-packages/twisted/application/app.py", line 579, in parseOptions
    usage.Options.parseOptions(self, options)
  File "/srv/graphite/site-packages/twisted/python/usage.py", line 255, in parseOptions
    self._dispatch[optMangled](optMangled, arg)
  File "/srv/graphite/site-packages/twisted/python/usage.py", line 411, in <lambda>
    fn = lambda name, value, m=method: m(value)
  File "/srv/graphite/site-packages/twisted/application/app.py", line 496, in opt_reactor
    raise usage.UsageError(msg)
UsageError: The specified reactor cannot be used, failed with error: reactor already installed.
See the list of available reactors with --help-reactors
```

**Comment by iain-buclaw-sociomantic** [comment]
Doesn't happen if I comment out from `lib/carbon/cache.py`
```
from twisted.internet import reactor
```

**Comment by mleinart** [comment]
@iain-buclaw-sociomantic Finally got around to fixing the startup if you'd like to try. The issue was with the reactor import - the Twisted reactor cant be imported until service start and adding the import to cache.py caused it to be imported through instrumentation.py through service.py when the service is first loaded, pre-start.
This fix for the import issue is IMO neither terrible nor great - ultimately we need to at some point reorganize to avoid circular imports and (maybe?) memoize the reactor. In the meantime, this keeps things running

**Comment by obfuscurity** [comment]
@mleinart This is an alternative to #551? Does anyone have time to benchmark these different approaches?

**Comment by mleinart** [comment]
Finally did some relatively thorough performance testing on this and... We shouldn't merge it.

While this did not appear to have any negative effect on my (modest) production install, when I simulated the worst-case scenario (tons of simultaneous updates from different agents with a high MAX_UPDATES_PER_SEC) CPU usage was significantly higher.

In contrast, in performing the same tests with #551, I found no observable difference in performance. These results are completely contrary to my expectation but.. ¯\_(ツ)_/¯ the numbers dont lie

**Pull request closed without merging**
