### PR TITLE
add zlib support.

### PR DESCRIPTION
**Pull request by dnozay**
I like the hassle-free UDP transport for sending packets,
and I like zlib for sending a lot of data in smaller packets.

### CODE REVIEW

**Comment by obfuscurity** [comment]
I'm torn on this patch. In one case, it sounds like a neat feature add. OTOH, I can't find a single instance where a user has requested compression. I'm tempted to rebase and resubmit this, but I'm a little concerned that you deemed the change worthy enough to add yourself to the Copyrights.

/cc @drawks @SEJeff @jssjr @mleinart for opinions

**Comment by jssjr** [comment]
This looks like a useful way to reduce packet-per-second on the receiver at the expense of higher CPU load due to decompression overhead. I can see situations where this might be worthwhile.

The copyright modification isn't needed and should be removed. Though, it would be nice to have an AUTHORS file.

**Comment by dnozay** [comment]
should the milestone be updated to 1.2.0?

**Comment by piotr1212** [comment]
This is an old one. Needs to be rebased and made compatible with py3.

**Pull request closed without merging**
