### PR TITLE
Don't use mirrors for pip

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by obfuscurity** [comment]
Why? /cc @brutasse @SEJeff

**Comment by alex** [comment]
The flag doesn't do anything on modern pips, and on older pips it doesn't actually help with uptime. /cc @dstufft

**Comment by obfuscurity** [comment]
Ah ok, I see that now in their release notes. Shows you how carefully I pay attention to pip releases. :wink: Thanks!

**Comment by brutasse** [comment]
:+1:

**Comment by alex** [comment]
np, sorry I didn't explain the reason in the original PR.

**Pull request merged**
