### PR TITLE
quick pass at UT for naive cache strategy

### PR DESCRIPTION
**Pull request by ross**
- also correct a copy-n-paste bug in the docstring of max

ran across the lack of naive testing during the course of reading/learning the code and wrote it up as part of that.

### CODE REVIEW

**Comment by obfuscurity** [comment]
@SEJeff what do you think of this?

@ross I really appreciate your contribution, but it would be better to target the master branch. Would you mind resubmitting this patch against master?

**Comment by SEJeff** [comment]
Looks totally reasonable to me. Not the biggest fan that the result ordering is non-deterministic and the way the test has to be written due to that, otherwise looks great.

@ross: thank you for doing this. We all hack on graphite in our very precious free time and contributors who add tests "just because" pretty much make my day. However, would you mind opening a PR against master please? We are very very soon going to stop accepting contributions when the next 0.9.x release is cut.

**Comment by obfuscurity** [comment]
@SEJeff I'm not fond of merging anything "new" into 0.9.x at this point, but if you want to push the button I'll :eyes: the other way. :wink:

**Comment by ross** [comment]
Sorry, the notification email arrived when I was traveling and was dropped until now. Took a quick look at master and I'm not sure the changes here make sense any more. The strategy stuff has been reworked and it looks like the 3 of them now have tests. Lmk if I'm missing something. Otherwise I guess this can be closed/abandoned.

**Comment by SEJeff** [comment]
No I entirely agree. @ross would you mind please redoing this PR against the master branch?

We are always down for more tests, please do send us more :)

It is just that we are trying to severely limit merging stuff to master so that we can release 0.9.13 and then put the `0.9.x` branch on ice Han Solo style.

**Comment by ross** [comment]
> No I entirely agree. @ross would you mind please redoing this PR against the master branch?

I looked at it, but the tests I'm adding here are already there so there's no reason to.

**Comment by obfuscurity** [comment]
No worries, gonna go ahead and close this out. Thanks for the contribution anyways. :heart: :zap: :beers:

**Pull request closed without merging**
