### PR TITLE
Lock writes to MetricCache size and dictionary

### PR DESCRIPTION
**Pull request by iain-buclaw-sociomantic**
My attempt at trying to address #528.

I don't really like the idea of it, as it slows down the cache.  However this was the best case method I could find.

Using this as a base benchmark:
```
Benchmarking single metric MetricCache store...
    datapoints: 1000       msecs: 1
    datapoints: 10000      msecs: 19
    datapoints: 100000     msecs: 174
    datapoints: 1000000     secs: 1.71134
Benchmarking unique metric MetricCache store...
    datapoints: 1000       msecs: 3
    datapoints: 10000      msecs: 33
    datapoints: 100000     msecs: 321
    datapoints: 1000000     secs: 3.2306
Benchmarking single metric MetricCache drain...
CACHE_WRITE_STRATEGY: max
    datapoints: 1000       usecs: 202
    datapoints: 10000      msecs: 1
    datapoints: 100000     msecs: 31
    datapoints: 1000000    msecs: 319
CACHE_WRITE_STRATEGY: naive
    datapoints: 1000       usecs: 168
    datapoints: 10000      msecs: 1
    datapoints: 100000     msecs: 31
    datapoints: 1000000    msecs: 318
CACHE_WRITE_STRATEGY: random
    datapoints: 1000       usecs: 174
    datapoints: 10000      msecs: 1
    datapoints: 100000     msecs: 32
    datapoints: 1000000    msecs: 319
CACHE_WRITE_STRATEGY: sorted
    datapoints: 1000       usecs: 313
    datapoints: 10000      msecs: 2
    datapoints: 100000     msecs: 31
    datapoints: 1000000    msecs: 318
Benchmarking unique metric MetricCache drain...
CACHE_WRITE_STRATEGY: max
    datapoints: 1000       msecs: 2
    datapoints: 10000      msecs: 27
    datapoints: 100000     [skipped]
    datapoints: 1000000    [skipped]
CACHE_WRITE_STRATEGY: naive
    datapoints: 1000       msecs: 2
    datapoints: 10000      msecs: 27
    datapoints: 100000     msecs: 277
    datapoints: 1000000     secs: 2.87606
CACHE_WRITE_STRATEGY: random
    datapoints: 1000       msecs: 2
    datapoints: 10000      msecs: 28
    datapoints: 100000     msecs: 279
    datapoints: 1000000    [skipped]
CACHE_WRITE_STRATEGY: sorted
    datapoints: 1000       msecs: 2
    datapoints: 10000      msecs: 28
    datapoints: 100000     msecs: 280
    datapoints: 1000000     secs: 2.88072
```
With this change, there was a 20% slowdown, with #527 there was a 40% slowdown.

### CODE REVIEW

**Comment by obfuscurity** [comment]
@iain-buclaw-sociomantic But the $64M question: does it fix the size reporting bug?

**Comment by deniszh** [comment]
20%  slowdown just for reporting cache size? O_o

**Comment by iain-buclaw-sociomantic** [comment]
> But the $64M question: does it fix the size reporting bug?

Graphs of carbon caches from the last 13 weeks.

carbon-cache

Never drops below zero.

> 20% slowdown just for reporting cache size? O_o

20% slowdown in draining the cache to zero in a serialized fashion, the benchmark itself it not very representative of real-life workloads where you have push and pops going in simultaneously.

But the meaning would be where it took `280ms` to drain 100,000 metrics, it now takes `320ms`.  Or `2.8 secs` to drain 1,000,000 metrics now takes `3.2 secs`.  I don't think this is a real problem, or at least if like me you only deal with an incoming 10K metrics every second.

**Comment by deniszh** [comment]
Ah, good, thanks for explanation, @iain-buclaw-sociomantic !

**Comment by iain-buclaw-sociomantic** [comment]
FYI, to explain that rise in cache towards the end, looks like I hit 100% CPU after the number of incoming metrics rose to 20K metrics a second using this patch.  YMMV, but I guess that could be an indicator of how much one carbon daemon with this patch can take before you need to start adding more.

**Comment by iain-buclaw-sociomantic** [comment]
That was quick @obfuscurity.  Shouldn't this patch be scrutinized? :smiley:

**Comment by obfuscurity** [comment]
Quick?

**Comment by obfuscurity** [comment]
@iain-buclaw-sociomantic The patch itself looked reasonable to me and you've presented sane benchmark numbers. @mleinart scrutinized it a fair amount already and expressed to me his preference for this one over #527. Is there anything else you're concerned with, i.e. reason to revert this?

**Comment by iain-buclaw-sociomantic** [comment]
Not from me.  I've been running this in production pretty much since this May.  I am more curious if there are better alternatives to a global thread lock.

**Comment by mleinart** [comment]
Also of note, this same locking strategy was in use for many years
until fe7686f40 removed it.

My best guess as to why it doesnt seem to have much if any impact is that
we're only sharing these cache operations between two threads. As I
understand it, when a locked Lock is encountered, Python will context
switch to another thread in the hopes that that thread either wont be
waiting on it or will have it and free it up. In our case, that's true 100%
of the time - if the reactor thread encounters it, the writer thread is
locking it and needs to continue and vice versa.

I agree a lock like this seems brute force, but the "right way" to do it in
Twisted land as I understand it is the approach in #527 where anything
requiring access to the shared state is run on the reactor thread. Since
that seems to have a significant performance penalty (in one set of tests I
measured 60% Carbon cpu usage with that strategy vs 20% baseline), this
seems our best option at the moment

**Comment by obfuscurity** [comment]
I haven't seen anything better yet. I'd still rather have it reported accurately with a "slight" performance penalty than emit bad stats. Hopefully we can iterate on this but we should definitely get it fixed in-tree for the time being.

**Comment by obfuscurity** [comment]
Follow-up bit of info. I ran another round of benchmarks on some very fast NVME flash drives (two of them striped with LVM) to get some anecdotal comparisons before and after this change. There was very little visible change in performance with the exception of system load **decreasing** after this change. Fascinating.

In each of these graphs, the first test (1430-1520) was running d4a6a83536acb00cc31c00fe642aa20e6dbf8f7d. The second test (1530-) was running dfc1d75969cc4fe4309207e80ea4cf3c5e03c977.

screen shot 2016-09-08 at 12 29 52 pm
screen shot 2016-09-08 at 12 29 57 pm
screen shot 2016-09-08 at 12 30 04 pm
screen shot 2016-09-08 at 12 30 10 pm
screen shot 2016-09-08 at 12 30 20 pm
screen shot 2016-09-08 at 12 30 37 pm
screen shot 2016-09-08 at 12 30 42 pm

**Comment by obfuscurity** [comment]
In case anyone's curious I was using https://github.com/gorsuch/haggar (on a separate host) to generate the benchmark data thusly:

```
GOPATH=~/gocode ./gocode/bin/haggar -agents=200 -metrics=4000 -carbon="x.x.x.x:2003"
```

**Pull request merged**
