### PR TITLE
fix MetricCache KeyError

### PR DESCRIPTION
**Pull request by shadow4125**
When I ran carbon-cache I can see the errors in console.log:
```
22/12/2015 08:48:26 :: Unhandled Error
Traceback (most recent call last):
  File "/home/q/graphite/lib/python2.7/site-packages/twisted/protocols/basic.py", line 755, in dataReceived
    self.stringReceived(packet)
  File "/opt/graphite/lib/carbon/protocols.py", line 126, in stringReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 72, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/pipeline.py", line 25, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/graphite/lib/carbon/cache.py", line 32, in process
    MetricCache.store(metric, datapoint)
  File "/opt/graphite/lib/carbon/cache.py", line 162, in store
    self[metric][timestamp] = value
exceptions.KeyError: 't.shadow.test'
```
I see store() setdefault dict first
```
self.setdefault(metric, {})
```
but, maybe this time pop()
```
datapoint_index = dict.pop(self, metric)
```
so I use defaultdict replace dict

### CODE REVIEW

**Comment by iain-buclaw-sociomantic** [comment]
I'm seeing this too.

**Comment by mleinart** [comment]
This looks like a race condition to me: a pop is happening sometime after the setdefault but before the datapoint is actually stored. It turns out setdefault() behaves like a check-and-set, i.e. the pop() will remove what it did (if anything).

I have an idea to fix the race, but I don't see a reason against just using a defaultdict here so I think I'm :+1: on this

**Comment by iain-buclaw-sociomantic** [comment]
Should probably do something like in the 0.9.x branch? https://github.com/graphite-project/carbon/blob/ae1464d02728e22298ff480296410caae381d025/lib/carbon/cache.py#L18-L21

**Comment by deniszh** [comment]
@iain-buclaw-sociomantic 
IIRC that's a workaround for python 2.6 and we're pointing to 2.7 compatibility to master. So, up to you. Do not hurt but do not need.

**Comment by mleinart** [comment]
IIRC we're still nursing along 2.4 support in 0.9.x. There's a pure python backport of defaultdict in carbon.util in 0.9.x branch but it's not any more threadsafe than the current way of doing it. One option for 0.9.x would be to re-add locks that were taken out in fe7686f4097dc9c81bb75f001b1cdde8d29fa251.

I'm surprised that we've gone so long without seeing reports of this though. @iain-buclaw-sociomantic @shadow4125 how often are you seeing this and what version of Python are you on?

**Comment by iain-buclaw-sociomantic** [comment]
@mleinart - This is the first time I encountered it, but it happened twice on two isolated servers running carbon-cache within the space of a week of each other - both having an uptime of no more than 10 days.

Some important things to note about my environment which have likely lead to this:
- A couple of weeks back we sorted out a problem where we were handling 4x more data than we should have been receiving.  So they are now no longer under heavy strain (writing out 180K metrics every 30 seconds).
- I am using the ``naive`` strategy I implemented, which admittedly gives this a higher chance to trigger compared to using ``sorted`` strategy.
- For me, this has only ever fired when the instrumentation service has sent a metric to cache.

I am running PyPy 4.0.1.

**Comment by iain-buclaw-sociomantic** [comment]
Saying that, when we were running handling 1M metrics per carbon-cache node, I would notice that the ``MetricCache.size`` would become a negative number after a few days of running.  Maybe it's a different issue altogether though (which I can see a likely fix for in that commit you linked):
```
+  @property
+  def size(self):
+    return reduce(lambda x, y: x + len(y), self.values(), 0)
```

**Comment by iain-buclaw-sociomantic** [comment]
>  Maybe it's a different issue altogether though (which I can see a likely fix for in that commit you linked)

Actually, applying that would cause a terrible performance regression if the cache were to grow very large.  Ignore me here. :-)

**Comment by mleinart** [comment]
Merging this since defaultdict is more clear here, fixes the immediate symptom, and doesnt seem to perform any worse. I'd also like to bring attention to #527 which should prevent any further races in this part of the code, including negative cache sizes mentioned above

**Comment by iain-buclaw-sociomantic** [comment]
Thanks, I'll give it a try out.

**Pull request merged**
