### PR TITLE
Tunable tcp backlog

### PR DESCRIPTION
**Pull request by jssjr**
Implements a config setting that exposes the TCP backlog parameter used when creating the listen socket for plain-text and pickle TCPServers. Also implements the backlog for the cache query server.

Note that this increases the default backlog to 1024, which in my opinion is a more realistic value for modern server hardware.

Fixes https://github.com/graphite-project/carbon/issues/324

### CODE REVIEW

**Comment by jssjr** [comment]
Before:

```
metrics-carbon1-cp1-stg.iad /proc/12556 # ss -lt  | grep 2113
LISTEN     0      50                      *:2113                     *:*
```

After:

```
metrics-carbon1-cp1-stg.iad /proc/12556 # ss -lt  | grep 2113
LISTEN     0      1024                    *:2113                     *:*
```

**Comment by mleinart** [comment]
:thumbsup:

**Comment by yuuki1** [comment]
:+1:

**Comment by syepes** [comment]
+1 This os a must have

**Pull request merged**
