### PR TITLE
add LRU cache and max size setting to relay to fix memory leak

### PR DESCRIPTION
**Pull request by bruce-lyft**
fix for https://github.com/graphite-project/carbon/issues/185

### CODE REVIEW

**Comment by mleinart** [comment]
This fix looks like it'll work to prevent the cache from growing unbounded, however I'm not sure it's practical to limit the size in this way.

Think about the typical metrics flow - generally each actively updating metric will be coming in at a regular interval, e.g. every 1 minute. If we have a limit of say 1000 items in this cache, only the last 1000 metrics seen in a given minute will be cached for the next inflow of metrics. If we assume the metrics come in roughly the same order, those 1000 will be evicted before they ever see a cache hit.

FWIW, I've committed be2e4f0d91 for now as suggested in #185 which should help in many cases, though I think it's still an open question as to whether it's a net gain caching these to avoid regex operations

**Comment by bruce-lyft** [comment]
@mleinart  The problem with the fix in be2e4f0 is that memory use is still unbounded.   In our case, we have new metrics coming in on a regular basis, with a short time horizon (collectd/statsd metrics that are per-host, for ephemeral hosts, but which are aggregated; for example, CPU average for a group of hosts).   Without this fix, we see carbon-aggregator memory use grow without bound and eventually crash.

**Comment by obfuscurity** [comment]
@bruce-lyft I think the aggregator leak in #185 is almost certainly the result of feeding aggregated metrics back into the aggregator loop as described in #455 and #560. There's a proposed fix in #439 but it needs some TLC before we can merge it. There's also an external fix applied to https://github.com/criteo-forks/carbon/commit/825693c97e57c7cdc36d0b0d758694010ce2be53 but I'd like to get feedback from others before we consider either of these.

/cc @mleinart @drawks @iain-buclaw-sociomantic

**Comment by obfuscurity** [comment]
Deleting my previous comment and moving it to #185.

**Comment by obfuscurity** [comment]
Closing as discussed in https://github.com/graphite-project/carbon/issues/185#issuecomment-246122400.

**Pull request closed without merging**
