### PR TITLE
protocols: enable traffic shaping with ShapedProtocolFactory()

### PR DESCRIPTION
**Pull request by iksaif**
This is using https://github.com/twisted/twisted/blob/HEAD/src/twisted/protocols/htb.py
to try to apply some traffic shaping to incoming connections.

### CODE REVIEW

**Comment by deniszh** [comment]
Traffic shaping? Interesting.
Does it really helps with some issues, @iksaif ?

**Comment by iksaif** [comment]
I'll add something to carbon.conf.example and try to get a graph that shows how it helps.

The idea is that we had some very big users sending bursts of ~300MiB of metrics and this would be starving others when these metrics had to be relayed on inter-continental links on the next hop.

This shapes the burst and make the metric receiver more fair.

**Comment by deniszh** [comment]
Cool, looks nice!

**Comment by deniszh** [comment]
Still want to improve that, @iksaif ?

**Comment by iksaif** [comment]
Getting some graphs is still on my todo list, I'll ping this issue when ready :)

**Comment by iksaif** [comment]
Probably will never get this done

**Pull request closed without merging**
