### PR TITLE
hashing, fix bisect on py3

### PR DESCRIPTION
**Pull request by piotr1212**
fixes: #766

### CODE REVIEW

**Comment by DanCech** [comment]
Looks good at first glance, this code is duplicated in graphite-web so you'll want to open a PR there also.

**Comment by piotr1212** [comment]
@DanCech What about removing the code from graphite-web and importing from carbon? is there some reason why that is not wanted except for web depending on carbon?

**Comment by deniszh** [comment]
That's possible, but please note that carbon requires e.g. Twisted, so, it will bring more dependencies to graphite-web. Not the end of the world, though.

**Comment by piotr1212** [comment]
Hmm, will leave it separate for now.

**Comment by ccope** [comment]
There's a stray swp file in the commit

**Comment by piotr1212** [comment]
removed the swp file

**Pull request merged**
