### PR TITLE
Enable whisper caching

### PR DESCRIPTION
**Pull request by pu239ppy**
Exposes cache enablement and age limit through settings
Launches a looping task in order to age items out of a cache
relies on https://github.com/graphite-project/whisper/pull/157

### CODE REVIEW

**Comment by bmhatfield** [comment]
As a devils advocate, I'd advise that trying to cache these headers in a per-process way (for each carbon as well as every python/django process) is very inefficient (on my system, I would end up with about 10 copies of the same "cache") and leads to worse overall performance than if we left this memory unused by python and let the filesystem cache manage them instead.

See also: https://github.com/graphite-project/carbon/issues/497#issuecomment-163949580

**Comment by pu239ppy** [comment]
Brian, this setting is not mandatory, and in fact disabled by default.
While it would be possible to have a unified cache with a caching system I
am reluctant to add more components (caching layer such as redis) to
carbon.

**Comment by bmhatfield** [comment]
Thanks for the additional context. I agree that disabled by default, if we go forward, is a good approach for introducing new behaviors such as this.

I guess my statement could be restated in the form of a question: Why add this, or a common caching layer like Redis (which already exists in Graphite as memcached), when the "do nothing and let the Linux filesystem cache handle it" is the most efficient and performant outcome?

Anyways, if other folks see value in this and want to move forward, I don't need to block this change further.

**Comment by pu239ppy** [comment]
If I recall correctly memcache only exists on graphite web, carbon does not reply on external services.  The filesystem buffers to which I assume you refer as as the "do nothing and let the Linux filesystem cache handle it" are not deterministic and are not guaranteed to keep the data I need.  Although it would be interesting to see what hits/misses I encounter (would have to figure out how to instrument that)

**Comment by obfuscurity** [comment]
Yes, but Whisper also relies on Graphite-Web to read data. Well, technically anything can use the Whisper library, but is that the use case (non-Graphite-Web readers) this is intended to address?

**Comment by pu239ppy** [comment]
These particular enhancement work in concert *only* to improve the performance of metric write operations.  Currently a write operation entails a read in to retrieve the whisper header.  This read is what I want to eliminate, in fact in whisper.py someone already took the steps toward that, I am merely enhancing this process by introducing per item expiration to the cache entry and a looping task to manage that expiry.

**Comment by iksaif** [comment]
I had to enable header caching once on carbon before we disabled buffering on reads in whisper. It helped a little bit reducing the load, not much though.

On biggraphite (https://github.com/criteo/biggraphite) we ended up using LMDB to share the cache across multiple processes. memcached was simply too slow for writes: you can't spend 1ms each time you write a point.

**Comment by piotr1212** [comment]
fwiw: I once tested performance gains with CACHE_HEADER = True hardcoded in whisper.py on  a production system (> 2.000.000 unique metrics) and didn't found any noticable performance improvements. I assumed that the file is read anyway for aggregation and the header got read from fs-cache, not causing any additional io to the disks.

this might have changed since the buffering patch:  https://github.com/graphite-project/whisper/commit/a3efa8453df65554e3636a32dbf39a1a4032993f

**Comment by iksaif** [comment]
CACHE_HEADER = True will only help if you are low on memory for the buffer cache. But you're right, most of the time this is cached by the os anyway.

**Pull request closed without merging**
