### PR TITLE
Adding CI for PPC64LE

### PR DESCRIPTION
**Pull request by ezeeyahoo**
Hi,

I have added config to enable CI on PPC64LE, request you to please review.
https://travis-ci.com/github/ezeeyahoo/carbon/builds/192061013

Thanks

### CODE REVIEW

**Comment by deniszh** [comment]
Hi @ezeeyahoo,

Thanks for your contribution! Question - do you have any PPC64 Linux system in production? I would not bloat building infra without particular reason, but if you really need that - we would like to help!

**Comment by gerrith3** [comment]
We have several thousand machines in production, including hundreds of e980's in our public cloud offering.   So, yes, lots of use in the Global 500 companies and all around the world.

**Comment by deniszh** [comment]
OK, we can try that. I hope it will work - despite Travis' shortage of free platform usage for OSS project.

**Comment by gerrith3** [comment]
@deniszh I'm looking into their new policy to see if we can refine it a bit.  It is pushing people away from Travis which is rather unfortunate.  I believe the policy is going to need some tuning.

**Comment by deniszh** [comment]
@gerrith3 
Well, I understaand their struggle, and they saying "please talk to us if you need more". So, let's merge it and we'll find out how it works.

**Pull request merged**
