### PR TITLE
Adds logging about why an input line is invalid

### PR DESCRIPTION
**Pull request by hufman**

### CODE REVIEW

**Comment by withnale** [comment]
How about making this not log if the line length is zero? We use tcp-open healthchecks on our load balancer and have a local patch for disabling huge numbers of these entries...

**Comment by SEJeff** [comment]
@withnale: care to send a PR?

**Comment by toni-moreno** [comment]
+1:
This will be very usefull to debug metrics !!

**Comment by obfuscurity** [comment]
I would :heart: to see tests for this.

**Comment by obfuscurity** [comment]
Conflict resolved and merged in #436. Thanks!

**Pull request merged**
