### PR TITLE
Add support for minimum datapoints per update

### PR DESCRIPTION
**Pull request by obfuscurity**
Sorry for the PR spam, need to recreate this one again after a merge conflict (my git fu is just _terribad_). Deprecates the work in #437 which in turn replaced #231. I'd like to find a better var than `mdpu`, looking for suggestions.

### CODE REVIEW

**Comment by obfuscurity** [comment]
There's something broken with this change. Caches are neither able to create new files or write to existing ones. I'll try to look into this closer as time permits but I've removed it from the 1.0.0 milestone for now.

**Comment by obfuscurity** [comment]
@pratX I know it's been a long time coming but if you have time to look at this it would be greatly appreciated.

**Comment by pratX** [comment]
I will look into this.

**Comment by iksaif** [comment]
Looked briefly at this because I want something similar. The idea is interesting but it looks like the implementation could use some love

**Comment by Exocomp** [comment]
Did this feature make it to production?

**Comment by deniszh** [comment]
@Exocomp - unfortunately not. I rebased it in #692 but not sure is it worth inclusion.
If you interested in this change - please test how it works.
Please also check timesorted writing strategy - it's a bit different, but maybe it's better fix then MDPU.

**Comment by deniszh** [comment]
Closed in favor of #692

**Comment by Exocomp** [comment]
@deniszh would the idea be to use MIN_TIMESTAMP_LAG with timesorted strategy ?

**Comment by deniszh** [comment]
@Exocomp - I'm not sure what's problem are you trying to solve, probably MIN_TIMESTAMP_LAG is a solution, probably not. What are you trying to achieve?

**Comment by Exocomp** [comment]
@deniszh basically to put a delay in writing so you get the effect of "batch" writes.  I like the idea of minimum data point per update but I do see how timesorted with MIN_TIMESTAMP_LAG can help - would be good if we had both (if I'm thinking about it right).

**Comment by Exocomp** [comment]
@deniszh I should add that I'm working with a system where the disk is not able to keep up with the small writes, it is basically killing all its throughput.

**Comment by deniszh** [comment]
@Exocomp : TBH I do not really understand how you can have both - for now I just exclude MDPU from timesorted strategy. 
How do we need to combine it - would we 
1) select metrics which have more than MIN_DATAPOINTS_PER_UPDATE datapoints in cache _AND_ already MIN_TIMESTAMP_LAG seconds
or 
2) select metrics which have more than MIN_DATAPOINTS_PER_UPDATE datapoints in cache _OR_ already MIN_TIMESTAMP_LAG seconds ?

**Comment by deniszh** [comment]
Or maybe it's better to implement MPDU only in separate strategy, and not for all strategies? I'm worried a bit that MPDU trying to change the default behavior of all strategies now...

**Comment by Exocomp** [comment]
@deniszh 

> select metrics which have more than MIN_DATAPOINTS_PER_UPDATE datapoints in cache OR already MIN_TIMESTAMP_LAG seconds

I like this _greedy_ method.

**Comment by deniszh** [comment]
@Exocomp : OK, added that grredy logic to timesorted strategi in #692. Completely not tested, though - any feedback appreciated.

**Comment by Exocomp** [comment]
Sweet!

**Comment by deniszh** [comment]
Well, current implementation should be fixed - with default MIN_DATAPOINTS_PER_UPDATE == 1 it's effectively turns timesorted strategy to sorted. I'm still thinking about implementing MDPU only for selected strategies, e.g. Max and Timesorted.

**Pull request closed without merging**
