### PR TITLE
Monkeypatch twisted logger to fix thread/umask bug

### PR DESCRIPTION
**Pull request by obfuscurity**
This is a proposed fix from @jacobrichard for the [Twisted umask race bug](https://twistedmatrix.com/trac/ticket/7026) as reported in #82. It would be **really** nice to finally squash this 5+ year-old bug, once and for all.

**PLEASE TEST THIS CHANGE AND REPORT BACK**

### CODE REVIEW

**Comment by ShalomCohen** [comment]
I couldn't make it work on 0.9.10, it seems exactly the same as the 0.9.13 file - are you sure this one is backward compatible - I just mentioned it on the 0.9.13 commit thread as well.

**Comment by jacobrichard** [comment]
In a test pulling from the current master branch, I see some issues with missing imports for the 'os' library. That was a miss on my part in my commit, sorry for the confusion.

The relevant code is in ba2328d097ebf41672711f429f0348b603135adb

**Comment by obfuscurity** [comment]
@jacobrichard Sorry, I don't see the problem with the way we're importing `exists`. Can you elaborate?

```python
Python 2.7.10 (default, Jul  9 2015, 13:34:07)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from os.path import exists
>>> exists('LICENSE')
True
>>> exists('foo')
False
```

**Comment by obfuscurity** [comment]
@jacobrichard Disregard, I see what you mean. Fixing.

**Pull request merged**
