### PR TITLE
Aggregation pipeline was broken.

### PR DESCRIPTION
**Pull request by cbowman0**
There was no documentation or example configs showing the need to set AGGREGATION_WRITE_BACK_FREQUENCY.

Error was:
```
12/01/2017 20:38:41 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/pypy/dist-packages/twisted/protocols/basic.py", line 765, in dataReceived
    self.stringReceived(packet)
  File "/opt/graphite/lib/carbon/protocols.py", line 107, in stringReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 62, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/pipeline.py", line 25, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/graphite/lib/carbon/aggregator/processor.py", line 58, in process
    buffer.configure_aggregation(rule.frequency, rule.aggregation_func)
  File "/opt/graphite/lib/carbon/aggregator/buffers.py", line 57, in configure_aggregation
    self.compute_task.start(settings['AGGREGATION_WRITE_BACK_FREQUENCY'] or int(frequency), now=False)
  File "/opt/graphite/lib/carbon/conf.py", line 117, in __getitem__
    raise ConfigError("Missing expected configuration \"%s\"" % key)
carbon.exceptions.ConfigError: <ConfigError(Missing expected configuration "AGGREGATION_WRITE_BACK_FREQUENCY")>
```

After setting the value in the config, the error moved to:
```
12/01/2017 21:14:28 :: Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/pypy/dist-packages/twisted/protocols/basic.py", line 454, in dataReceived
    self.lineReceived(line)
  File "/opt/graphite/lib/carbon/protocols.py", line 76, in lineReceived
    self.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/protocols.py", line 62, in metricReceived
    events.metricReceived(metric, datapoint)
  File "/opt/graphite/lib/carbon/events.py", line 20, in __call__
    handler(*args, **kwargs)
--- <exception caught here> ---
  File "/opt/graphite/lib/carbon/pipeline.py", line 25, in run_pipeline
    for out_metric, out_datapoint in processor.process(metric, datapoint):
  File "/opt/graphite/lib/carbon/aggregator/processor.py", line 58, in process
    buffer.configure_aggregation(rule.frequency, rule.aggregation_func)
  File "/opt/graphite/lib/carbon/aggregator/buffers.py", line 57, in configure_aggregation
    self.compute_task.start(settings['AGGREGATION_WRITE_BACK_FREQUENCY'] or int(frequency), now=False)
  File "/usr/lib/pypy/dist-packages/twisted/internet/task.py", line 175, in start
    self._reschedule()
  File "/usr/lib/pypy/dist-packages/twisted/internet/task.py", line 233, in _reschedule
    untilNextTime = (self._expectNextCallAt - currentTime) % self.interval
exceptions.TypeError: unsupported operand type(s) for %: 'float' and 'str'
```

This updates the example aggregation.conf and sets the default value to 0.

### CODE REVIEW

**Comment by obfuscurity** [comment]
Wait, this is against the megacarbon branch?

**Comment by obfuscurity** [comment]
Git blame says it was brought in by you anyways, so use your best judgement here. :wink:

**Comment by cbowman0** [comment]
Yes.  Against the megacarbon branch.  I'm attempting to reduce the changes I have to a small patch against megacarbon and then possibly I'll be able to rework my env to run master.  We'll see.

The extra config stuff was me, yes.  I don't know where that went or when.  The introduction of the AGGREGATION_WRITE_BACK_FREQUENCY is not me.

**Comment by cbowman0** [comment]
Looks to also be reported here: https://answers.launchpad.net/graphite/+question/282148

**Comment by deniszh** [comment]
It's against megacarbon, I think it's quite safe to merge.

**Pull request merged**
