### PR TITLE
hashing: fix performance regression

### PR DESCRIPTION
**Pull request by iksaif**
benchmarks before:
```
 consistent-hashing  deplication_factor: 1 diverse_replicas: 1 n_destinations: 1     datapoints: 100000 msecs: 36
 consistent-hashing  deplication_factor: 1 diverse_replicas: 1 n_destinations: 16    datapoints: 100000 msecs: 735
 consistent-hashing  deplication_factor: 1 diverse_replicas: 1 n_destinations: 32    datapoints: 100000 secs: 2.18479
 consistent-hashing  deplication_factor: 1 diverse_replicas: 1 n_destinations: 48    datapoints: 100000 secs: 5.39408
```

benchmarks after:
```
 consistent-hashing  replication_factor: 1 diverse_replicas: 1 n_destinations: 1     datapoints: 100000 msecs: 44
 consistent-hashing  replication_factor: 1 diverse_replicas: 1 n_destinations: 16    datapoints: 100000 msecs: 483
 consistent-hashing  replication_factor: 1 diverse_replicas: 1 n_destinations: 32    datapoints: 100000 msecs: 871
 consistent-hashing  replication_factor: 1 diverse_replicas: 1 n_destinations: 48    datapoints: 100000 secs: 1.36102
  
```

### CODE REVIEW

**Comment by iksaif** [comment]
https://github.com/graphite-project/graphite-web/pull/2191

**Comment by deniszh** [comment]
It will not touch hashing order, right?

**Comment by iksaif** [comment]
> It will not touch hashing order, right?

sets are not ordered, so order in which the nodes would have been returned will change. I though about that, but I also did not find when this could be an issue (since all returned nodes are always used). Did I miss anything ?

**Comment by deniszh** [comment]
Well. We have not perfect test coverage, but current tests are green, so, let's assuming that everything is good. 👍

**Comment by DanCech** [comment]
Yeah, looking at how it's used it seems like it should be fine.

**Pull request merged**
