### PR TITLE
[1.1.x] s390x support for travis (#869) | Fix #871: Adjust aggregator-rules input_pattern match greediness to support numeric matching after captured field (#872) | sanitize names when using them as tag value (#858) | sanitize names when us

### LINKED ISSUE #871: [BUG] carbon-aggregator input regexp match is greedy
**Describe the bug**
When using aggregator to aggregate metrics from nodes with a name such as "mycluster-location1" to "mycluster-location350" using a regexp with "mycluster-\<location\>\d+" the rule regexp breaks it out to summaries for "location", "location1", "location2" ... up to "location35" instead of "location".

**To Reproduce**
Configure aggregation-rule of:

aggregate.\<location\>.app.requests (60) = sum collectd.mycluster-\<location\>\d+.app.requests

Feed data with collectd.mycluster-helsinki150.app.requests, observe aggregated data point come out for aggregate.helsinki15.app.requests.

**Expected behavior**
Should not include the numbers matched by \d+ in the aggregate identiifer.

The issue appears to be in lib/carbon/aggregator/rules.py, regex_part setup, it should use the '?' non-greedy modifier suffix to make the match not greedy and let the user-supplied part on the right side be greedy. I have a tested patch, I will make a pull request shortly.

### PR DESCRIPTION
**Pull request by deniszh**
Backports the following commits to 1.1.x:
 - s390x support for travis (#869)
 - Fix #871: Adjust aggregator-rules input_pattern match greediness to support numeric matching after captured field (#872)
 - sanitize names when using them as tag value (#858)
 - sanitize names when using them as tag value (#858)
 - sanitize names when using them as tag value (#858)
 - Another test fix try (#874)
 - simplify travis-ci config (#875)
 - Fixing tests for S390 (#880)
 - Trying to fix tests (#881)
 - Fix the manhole for Twisted > 16 and Python 3 (#882)

### CODE REVIEW

**Comment by deniszh** [comment]
Preparing 1.1.7 release

**Comment by piotr1212** [comment]
pr858 is added three times? You might want to check what went wrong there.

**Comment by deniszh** [comment]
Same thing as with 2458 in https://github.com/graphite-project/graphite-web/pull/2545

It just inserting empty commits for some reason.

**Comment by deniszh** [comment]
I mean, PR is good, despite duping

**Pull request merged**
