### PR TITLE
Fix missing encoding for line protocol

### PR DESCRIPTION
**Pull request by pkruk**
PR for issue: https://github.com/graphite-project/carbon/issues/884

### CODE REVIEW

**Comment by piotr1212** [comment]
Thanks this should work but the tests need to be adjusted, see the travis results. You can ignore the deepsource results. There is also a trailing whitespace which breaks the lint check.

to run the tests locally just invoke `tox`.

**Comment by deniszh** [comment]
I disable Deepsource, maybe will remove it completely.

**Comment by pkruk** [comment]
@piotr1212 thanks! I will fix it!

**Comment by piotr1212** [comment]
tests are still failing, you can replace the expected values with the actual ones (just add the b in front of the string to indicate it is a bytearray)

**Comment by pkruk** [comment]
@piotr1212 Hey, I will fix it in a moment :) thanks!

**Pull request merged**
