### PR TITLE
Restore CH routing that replicas exist on different servers

### PR DESCRIPTION
**Pull request by dctrwatson**
Should put a note that 0.9.11+ is not backwards compatible due to this change

### CODE REVIEW

**Comment by deniszh** [comment]
@fhossain: nope, your fix is giving serious performace regression - please check  https://github.com/graphite-project/carbon/pull/175
So, we need to stick with @dctrwatson  fix.

**Comment by deniszh** [comment]
@dctrwatson, could you please explain rationale behind that change, please?

**Comment by dctrwatson** [comment]
It's been awhile.

iirc, the main reason was when upgrading, a majority percentage of replicas were "lost" in the routing change. Since without this, if a replicas hashed to the same host, it wouldn't try for the next slot like previously.

Also, from a availability standpoint, restarting or losing a host and having the the primary and replica(s) on the same host, could cause problems.

**Comment by deniszh** [comment]
Hello @dctrwatson ,
Good idea, but it will break existing clusters, am I right?

**Comment by dctrwatson** [comment]
Depends on when the cluster was created.
Created pre-routing change, this restores all the missing historical data.
Created post-routing change, then yes, it they will lose some/all their historical data.
(Both just applying to the replicas, not the primary)

**Comment by deniszh** [comment]
Hi @dctrwatson ,
Then I better to make this thing optional in #452 
Please review!
I close that in favour of #452 . Thanks for your contribution!

**Pull request closed without merging**
