### PR TITLE
Make protocols pluggable

### PR DESCRIPTION
**Pull request by iksaif**
- A server protocol just need to implement a build(root_service) class method that will add its service to the root service.
- A client protocol will need to inherit from CarbonClientFactory and implement clientProtocol().

This code was *not* tested with amqp and manhole because there are no unit tests and I do not have the infrastructure to test these.

First step towards #275.

### CODE REVIEW

**Comment by iksaif** [comment]
Will fix the tests today or tomorrow, but would love a first high level review :)

**Comment by obfuscurity** [comment]
@iksaif at a high-level it LGTM.

**Comment by deniszh** [comment]
Same here. Looking good, but I didn't test it.

**Comment by iksaif** [comment]
Will deploy it on our test setup on monday.

**Comment by deniszh** [comment]
Not good PR, @iksaif ?

**Comment by iksaif** [comment]
It's good, but I messed up with my git .. I'll re-upload it shortly

**Comment by iksaif** [comment]
This has been deployed in our test environment without issue.

**Pull request merged**
